### ISSUE TITLE
 Getting Application class not found error while running on Android 5 or 6

### ISSUE THREAD

**Issue by khagesh1998** [SgtSilvio/android-retrofix#16]
On adding the backport dependencies with retrofix plugin as per the below doc, we are getting attached stack crash:
https://hivemq.github.io/hivemq-mqtt-client/docs/installation/android/#android-api-levels-below-24

Also The JDK Version in the app is being used is JAVA_11.
Kindly help.

We have analysed this on sample app and found that when facebook sdk is used with android-retrofix  the app crashes but it works fine without [facebook sdk](https://github.com/facebook/facebook-android-sdk). 

The issue was previously raised on the associated dependencies [android-retrofuture](https://github.com/retrostreams/android-retrofuture/issues/5) but it has been pointed out that there is no issue with [RetroFuture](https://github.com/retrostreams/android-retrofuture/)

```
  Process: com.app.staging, PID: 21740
                                                                                                    java.lang.RuntimeException: Unable to instantiate application com.example.Application: java.lang.ClassNotFoundException: Didn't find class  com.example.Application on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.app.staging-1/base.apk"],nativeLibraryDirectories=[/data/app/com.app.staging-1/lib/arm, /data/app/com.app.staging-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                                                    	at android.app.LoadedApk.makeApplication(LoadedApk.java:581)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4817)
                                                                                                    	at android.app.ActivityThread.access$1700(ActivityThread.java:166)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1475)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loop(Looper.java:148)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:5619)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class  com.example.Application on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.app.staging-1/base.apk"],nativeLibraryDirectories=[/data/app/com.app.staging-1/lib/arm, /data/app/com.app.staging-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                                    	at android.app.Instrumentation.newApplication(Instrumentation.java:988)
                                                                                                    	at android.app.LoadedApk.makeApplication(LoadedApk.java:576)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4817) 
                                                                                                    	at android.app.ActivityThread.access$1700(ActivityThread.java:166) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1475) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                    	at android.os.Looper.loop(Looper.java:148) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:5619) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:853) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737) 
                                                                                                    	Suppressed: java.lang.NoClassDefFoundError: com.example.Application
                                                                                                    		at dalvik.system.DexFile.defineClassNative(Native Method)
                                                                                                    		at dalvik.system.DexFile.defineClass(DexFile.java:226)
                                                                                                    		at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                                                                                                    		at dalvik.system.DexPathList.findClass(DexPathList.java:338)
                                                                                                    		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                                                                    		... 13 more
                                                                                                    	Suppressed: java.lang.ClassNotFoundException: com.example.Application
                                                                                                    		at java.lang.Class.classForName(Native Method)
                                                                                                    		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                                    		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                                    		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                                    		... 12 more
                                                                                                    	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by SgtSilvio** [comment]
Hi @khagesh1998 
It seems very strange that this error is related to android-retrofix, because it does not remove classes.
(Unnecessary) classes are usually removed by a code shrinker like proguard or R8.
To be able to help you here, please provide the following information:
1. Is `com.example.Application` the main class of your app?
2. Please take a look into your apk file. Does it contain the class `com.example.Application`?
3. Does the apk file contain all other classes of your app?
4. Can you share your build scripts?
5. If you can not share your whole build script, can you share the list of plugins and any proguard configuration?

**Comment by SgtSilvio** [comment]
> We have analysed this on sample app

Can you share the whole sample app?

**Comment by SgtSilvio** [comment]
I will close this as I did not receive an answer. We can reopen this issue if you still have the issue and you comment on my questions.
