### ISSUE TITLE
NoSuchFileException when building Kotlin project

### ISSUE THREAD

**Issue by gwimmel** [SgtSilvio/android-retrofix#5]
We get a `NoSuchFileException` when building our Kotlin project with RetroFix 0.3.0:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithAndroidRetroFixFor<flavor>Debug'.
...
Caused by: java.lang.RuntimeException: java.nio.file.NoSuchFileException: META-INF/app_<flavor>Debug.kotlin_module
        at com.github.sgtsilvio.gradle.android.retrofix.util.Lambdas.lambda$predicate$1(Lambdas.java:45)
        at com.github.sgtsilvio.gradle.android.retrofix.RetroFixTransform.lambda$transform$6(RetroFixTransform.java:132)
        at com.github.sgtsilvio.gradle.android.retrofix.util.Lambdas.lambda$consumer$0(Lambdas.java:33)
        ... 85 more
Caused by: java.nio.file.NoSuchFileException: META-INF/app_<flavor>Debug.kotlin_module
        at com.github.sgtsilvio.gradle.android.retrofix.RetroFixTransform.lambda$transform$2(RetroFixTransform.java:126)
        at com.github.sgtsilvio.gradle.android.retrofix.util.Lambdas.lambda$predicate$1(Lambdas.java:43)
        ... 87 more
```

I did some analysis: in RetroFixTransform:116 inputPath is `/home/.../app/build/tmp/kotlin-classes/<flavor>Debug`. This directory contains a file `META-INF/app_<flavor>Debug.kotlin_module`. The path is relativized in RetroFixTransform:118, so in RetroFixTransform:126 it tries to copy `META-INF/app<flavor>Debug.kotlin_module` (relative path) to `/home/.../app/build/intermediates/transforms/androidRetroFix/<flavor>/debug/281/META-INF/app_<flavor>Debug.kotlin_module`. The relative source path is not found.

In Retrofix 0.2.1, the build does not fail, because there is a try-catch clause which was removed in https://github.com/SgtSilvio/android-retrofix/commit/3e9479bb6752fe766532d612e42bbbc90a7fb2cb .

We can provide further information if necessary.

**Comment by SgtSilvio** [comment]
Thanks for reporting.
Is fixed in version 0.3.1 which I just released.

**Comment by gwimmel** [comment]
Thanks for the quick reply. I don't see any code changes between 0.3.0 and 0.3.1 though, am I missing something?

I tried 0.3.1 and my build seems to hang now at transformClassesWithAndroidRetrofixFor<flavor>Debug (not sure if it's something on my side, would have to analyze further).

**Comment by SgtSilvio** [comment]
Sorry, I did not push the changes before creating the tag on GitHub.
The published version was built locally.
I pushed the changes and deleted and recreated the release now.

**Comment by gwimmel** [comment]
works now, thanks again!
